### ISSUE TITLE
Plugin corrupted also reinstall do not solve

### ISSUE THREAD

**Issue by marcobra** [nextgis/osmpoly_export#7]
Error on loading QGIS 2.14.0-Essen

------------------------------------
Impossibile caricare il plugin osmpoly_export a causa di un errore chiamando il metodo classFactory() 

IOError: [Errno 2] File o directory non esistente: '/home/ubuntu/.qgis2/python/plugins/osmpoly_export/ui/aboutdialogbase.ui' 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 306, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/ubuntu/.qgis2/python/plugins/osmpoly_export/__init__.py", line 30, in classFactory
    from polygenerator import osmpoly_export
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/ubuntu/.qgis2/python/plugins/osmpoly_export/polygenerator.py", line 33, in 
    import aboutdialog
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/ubuntu/.qgis2/python/plugins/osmpoly_export/aboutdialog.py", line 38, in 
    FORM_CLASS, _ = uic.loadUiType(os.path.join(os.path.dirname(__file__), 'ui/aboutdialogbase.ui'))
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/__init__.py", line 208, in loadUiType
    winfo = compiler.UICompiler().compileUi(uifile, code_string, from_imports, resource_suffix)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/Compiler/compiler.py", line 140, in compileUi
    w = self.parse(input_stream, resource_suffix)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/uiparser.py", line 974, in parse
    document = parse(filename)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 647, in parse
    source = open(source, "rb")
IOError: [Errno 2] File o directory non esistente: '/home/ubuntu/.qgis2/python/plugins/osmpoly_export/ui/aboutdialogbase.ui'

Versione Python: 2.7.10 (default, Oct 14 2015, 16:09:02) [GCC 5.2.1 20151010] 
Versione di QGIS: 2.14.0-Essen Essen, exported 

Path di Python:
/usr/share/qgis/python
/home/ubuntu/.qgis2/python
/home/ubuntu/.qgis2/python/plugins
/usr/share/qgis/python/plugins
/usr/local/lib/python2.7/dist-packages/spiderosm-0.4.3-py2.7.egg
/usr/local/lib/python2.7/dist-packages/pyshp-1.2.1-py2.7.egg
/usr/local/lib/python2.7/dist-packages/geojson-1.0.9-py2.7.egg
/usr/local/lib/python2.7/dist-packages/pylev-1.3.0-py2.7.egg
/usr/local/lib/python2.7/dist-packages/Shapely-1.5.7-py2.7.egg
/usr/local/lib/python2.7/dist-packages/pyproj-1.9.4-py2.7-linux-x86_64.egg
/usr/lib/python2.7/dist-packages
/usr/local/lib/python2.7/dist-packages/python_telegram_bot-2.8.7-py2.7.egg
/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/home/ubuntu/.local/lib/python2.7/site-packages
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/PILcompat
/usr/lib/python2.7/dist-packages/gst-0.10
/usr/lib/python2.7/dist-packages/gtk-2.0
/usr/lib/pymodules/python2.7
/usr/lib/python2.7/dist-packages/ubuntu-sso-client
/usr/lib/python2.7/dist-packages/wx-3.0-gtk2
/home/ubuntu/.qgis2//python

Then deleting and reinstalling plugin i get:
![schermata del 2016-03-13 00-36-06](https://cloud.githubusercontent.com/assets/1607387/13726003/fb75b14a-e8b3-11e5-9546-e318806e8c00.png)

**Comment by simgislab** [comment]
one file was forgotten in the package, I should've tested it better.
